include(CheckIncludeFiles)
include(CheckTypeSize) 
include(CMakeDetermineSystem)
include(CheckFunctionExists)


## Check include files


check_include_files(ap/compat.h HAVE_AP_COMPAT_H)
check_include_files(ap/config.h HAVE_AP_CONFIG_H)
check_include_files(applicationservices/applicationservices.h HAVE_APPLICATIONSERVICES_APPLICATIONSERVICES_H)
check_include_files(arpa/inet.h HAVE_ARPA_INET_H)
check_include_files(arpa/nameser.h HAVE_ARPA_NAMESER_H)
check_include_files(assert.h HAVE_ASSERT_H)

check_include_files(build-defs.h HAVE_BUILD_DEFS_H)

check_include_files(cli0cli.h HAVE_CLI0CLI_H)
check_include_files(cli0core.h HAVE_CLI0CORE_H)
check_include_files(cli0defs.h HAVE_CLI0DEFS_H)
check_include_files(cli0env.h HAVE_CLI0ENV_H)
check_include_files(cli0ext.h HAVE_CLI0EXT_H)
check_include_files(crypt.h HAVE_CRYPT_H)
check_include_files(default/store.h HAVE_DEFAULT_STORE_H)
check_include_files(dirent.h HAVE_DIRENT_H)

check_include_files(errno.h HAVE_ERRNO_H)
check_include_files(fcntl.h HAVE_FCNTL_H)
check_include_files(giconv.h HAVE_GICONV_H)
check_include_files(grp.h HAVE_GRP_H)
check_include_files(ieeefp.h HAVE_IEEEFP_H)

check_include_files(iodbc.h HAVE_IODBC_H)
check_include_files(isql.h HAVE_ISQL_H)
check_include_files(isqlext.h HAVE_ISQLEXT_H)
check_include_files(langinfo.h HAVE_LANGINFO_H)
check_include_files(ldap/sasl.h HAVE_LDAP_SASL_H)
check_include_files(ldap/sasl/sasl.h HAVE_LDAP_SASL_SASL_H)
check_include_files(librarymanager.h HAVE_LIBRARYMANAGER_H)

check_include_files(locale.h HAVE_LOCALE_H)


check_include_files(memory.h HAVE_MEMORY_H)
check_include_files(monetary.h HAVE_MONETARY_H)
check_include_files(ncurses.h HAVE_NCURSES_H)
check_include_files(ndir.h HAVE_NDIR_H)
check_include_files(netdb.h HAVE_NETDB_H)
check_include_files(netinet/in.h HAVE_NETINET_IN_H)
check_include_files(netinet/tcp.h HAVE_NETINET_TCP_H)
check_include_files(odbc.h HAVE_ODBC_H)
check_include_files(odbcsdk.h HAVE_ODBCSDK_H)
check_include_files(old/compat.h HAVE_OLD_COMPAT_H)
check_include_files(pg/config.h HAVE_PG_CONFIG_H)
check_include_files(pwd.h HAVE_PWD_H)
check_include_files(resolv.h HAVE_RESOLV_H)

check_include_files(sql.h HAVE_SQL_H)
check_include_files(sqlcli1.h HAVE_SQLCLI1_H)
check_include_files(sqlext.h HAVE_SQLEXT_H)
check_include_files(sqltypes.h HAVE_SQLTYPES_H)
check_include_files(sqlucode.h HAVE_SQLUCODE_H)
check_include_files(sqlunix.h HAVE_SQLUNIX_H)
check_include_files(st.h HAVE_ST_H)

check_include_files(stdbool.h HAVE_STDBOOL_H)



check_include_files(strings.h HAVE_STRINGS_H)
check_include_files(sys/dir.h HAVE_SYS_DIR_H)
check_include_files(sys/file.h HAVE_SYS_FILE_H)
check_include_files(sys/ioctl.h HAVE_SYS_IOCTL_H)
check_include_files(sys/ipc.h HAVE_SYS_IPC_H)
check_include_files(sys/loadavg.h HAVE_SYS_LOADAVG_H)
check_include_files(sys/mkdev.h HAVE_SYS_MKDEV_H)
check_include_files(sys/mman.h HAVE_SYS_MMAN_H)
check_include_files(sys/mount.h HAVE_SYS_MOUNT_H)
check_include_files(sys/ndir.h HAVE_SYS_NDIR_H)
check_include_files(sys/param.h HAVE_SYS_PARAM_H)
check_include_files(sys/poll.h HAVE_SYS_POLL_H)
check_include_files(sys/resource.h HAVE_SYS_RESOURCE_H)
check_include_files(sys/select.h HAVE_SYS_SELECT_H)
check_include_files(sys/socket.h HAVE_SYS_SOCKET_H)
check_include_files(sys/stat.h HAVE_SYS_STAT_H)
check_include_files(sys/statfs.h HAVE_SYS_STATFS_H)
check_include_files(sys/statvfs.h HAVE_SYS_STATVFS_H)
check_include_files(sys/sysexits.h HAVE_SYS_SYSEXITS_H)

check_include_files(sys/times.h HAVE_SYS_TIMES_H)

check_include_files(sys/un.h HAVE_SYS_UN_H)
check_include_files(sys/utsname.h HAVE_SYS_UTSNAME_H)
check_include_files(sys/varargs.h HAVE_SYS_VARARGS_H)
check_include_files(sys/vfs.h HAVE_SYS_VFS_H)
check_include_files(sys/wait.h HAVE_SYS_WAIT_H)
check_include_files(sysexits.h HAVE_SYSEXITS_H)
check_include_files(syslog.h HAVE_SYSLOG_H)
check_include_files(termios.h HAVE_TERMIOS_H)
check_include_files(time.h HAVE_TIME_H)
check_include_files(tuxmodule.h HAVE_TUXMODULE_H)
check_include_files(udbcext.h HAVE_UDBCEXT_H)


check_include_files(utime.h HAVE_UTIME_H)
check_include_files(wchar.h HAVE_WCHAR_H)
check_include_files(xmlparse.h HAVE_XMLPARSE_H)
check_include_files(xmltok.h HAVE_XMLTOK_H)

## Check standard types and type sizes

check_type_size("char" SIZEOF_CHAR)
check_type_size("char *" SIZEOF_CHAR_P)
check_type_size("int" SIZEOF_INT)
check_type_size("intmax_t" SIZEOF_INTMAX_T)
check_type_size("long" SIZEOF_LONG)
check_type_size("long int" SIZEOF_LONG_INT)
check_type_size("long long" SIZEOF_LONG_LONG)
check_type_size("long long int" SIZEOF_LONG_LONG_INT)
check_type_size("ptrdiff_t" SIZEOF_PTRDIFF_T)
check_type_size("short" SIZEOF_SHORT)
check_type_size("size_t" SIZEOF_SIZE_T)
check_type_size("ssize_t" SIZEOF_SSIZE_T)


check_type_size("unsigned long" SIZEOF_ULONG)
if(APPLE)
  set(ulong "unsigned long")
endif(APPLE)

if(NOT SIZEOF_ULONG)
  set(ulong "unsigned long")
endif(NOT SIZEOF_ULONG)
message("sizeof(unsigned long) == ${SIZEOF_ULONG}")


#check_type_size("unsigned long" SIZEOF_LONG)
#check_type_size("unsigned long int" SIZEOF_LONG_INT)
#check_type_size("unsigned long long" SIZEOF_LONG_LONG)
#check_type_size("unsigned long long int" SIZEOF_LONG_LONG_INT)

#message("sizeof_long ${SIZEOF_LONG}")

# add, unsigned char, unsigned short, unsigned int, unsigned long, unsigned long long, throw error if not = 4
#if(HAVE_UINT32)
#  set(ulong uint32)
#elseif(SIZEOF_LONG EQUAL 4)
#  set(ulong "unsigned long")
#endif(HAVE_UINT32)

## Check libs

## Configigure for main/streams
check_include_files(glob.h HAVE_GLOB)

## Configure for Zend
message("** Configuration part for ZEND")
check_include_files(inttypes.h HAVE_INTTYPES_H)
check_include_files(stdint.h HAVE_STDINT_H)
check_include_files(limits.h HAVE_LIMITS_H)
check_include_files(malloc.h HAVE_MALLOC_H)
check_include_files(string.h HAVE_STRING_H)
check_include_files(unistd.h HAVE_UNISTD_H)
check_include_files(stdarg.h HAVE_STDARG_H)
check_include_files(sys/types.h HAVE_SYS_TYPES_H)
check_include_files(sys/time.h HAVE_SYS_TIME_H)
check_include_files(signal.h HAVE_SIGNAL_H)
check_include_files(unix.h HAVE_UNIX_H)
check_include_files(stdlib.h HAVE_STDLIB_H)
check_include_files(dlfcn.h HAVE_DLFCN_H)
## check if system is Darwin > 8
check_include_files(mach-o/dyld.h HAVE_MACH_O_DYLD_H)
check_type_size("size_t" SIZEOF_SIZE_T)
include(TestSignalType)
check_type_size("uint" SIZEOF_UINT)
check_type_size("ulong" SIZEOF_ULONG)
check_type_size("int32_t" SIZEOF_INT32_T)
check_type_size("uint32_t" SIZEOF_UINT32_T)

check_function_exists(vprintf HAVE_VPRINTF)
check_function_exists(_doprnt HAVE_DOPRNT)
check_function_exists(memcmp HAVE_MEMCMP)
check_include_files(alloca.h HAVE_ALLOCA_H)
check_function_exists(alloca HAVE_ALLOCA)
check_function_exists(memcpy HAVE_MEMCPY)
check_function_exists(getpid HAVE_GETPID)
check_function_exists(kill HAVE_KILL)
check_function_exists(finite HAVE_FINITE)
check_function_exists(fpclass HAVE_FPCLASS)
check_function_exists(sigsetjmp HAVE_SIGSETJMP)

# AC_ZEND_BROKEN_SPRINTF
# checking whether sprintf is broken... no

check_function_exists(finite HAVE_FINITE)
check_function_exists(isfinite HAVE_ISFINITE)
check_function_exists(isinf HAVE_ISINF)
check_function_exists(isnan HAVE_ISNAN)

check_function_exists(strcoll HAVE_STRCOLL)
check_function_exists(strdup HAVE_STRDUP)
check_function_exists(strerror HAVE_STRERROR)
check_function_exists(strfmon HAVE_STRFMON)
check_function_exists(strftime HAVE_STRFTIME)
check_function_exists(strlcat HAVE_STRLCAT)
check_function_exists(strlcpy HAVE_STRLCPY)
check_function_exists(strndup HAVE_STRNDUP)
check_function_exists(strndup HAVE_STRNDUP)
check_function_exists(strobrk HAVE_STRPBRK)
check_function_exists(strptime HAVE_STRPTIME)

check_function_exists(strstr HAVE_STRSTR)
check_function_exists(strtod HAVE_STRTOD)
check_function_exists(strtok_r HAVE_STRTOK_R)
check_function_exists(strtol HAVE_STRTOL)
check_function_exists(strtoll HAVE_STRTOLL)
check_function_exists(strtoul HAVE_STRTOUL)
check_function_exists(strtoull HAVE_STRTOULL)

check_function_exists(link HAVE_LINK)
check_function_exists(localeconv HAVE_LOCALECONV)
check_function_exists(localtime_r HAVE_LOCALTIME_R)
check_function_exists(lockf HAVE_LOCKF)
check_function_exists(log1p HAVE_LOG1P)
check_function_exists(lrand48 HAVE_LRAND48)
check_function_exists(makedev HAVE_MAKEDEV)


# ZEND_FP_EXCEPT


# ext/standard

# libxml
find_package(LibXml2)
if(LIBXML2_FOUND)
  set(HAVE_LIBXML 1)
  set(HAVE_DOM 1)
  include_directories(${LIBXML2_INCLUDE_DIR})
endif(LIBXML2_FOUND)

# fileinfo
check_function_exists(utime HAVE_UTIME)
check_function_exists(utimes HAVE_UTIMES)

# pcre
set(HAVE_BUNDLED_PCRE 1)
set(HAVE_BUILD_DEFS_H 1)
set(PHP_USE_PHP_CRYPT_R 1)
set(HAVE_STRNLEN 1)
set(HAVE_SYMLINK 1)
set(HAVE_CRYPT 1)
set(HAVE_CTYPE 1)
set(HAVE_HTONL 1)


check_function_exists(chroot ENABLE_CHROOT_FUNC)
check_include_files(sys/ioctl.h GWINSZ_IN_SYS_IOCTL)

check_function_exists(alphasort HAVE_ALPHASORT)
check_function_exists(asctime_r HAVE_ASCTIME_R)
check_function_exists(asinh HAVE_ASINH)
check_function_exists(alloca HAVE_ALLOCA)
check_function_exists(asprintf HAVE_ASPRINTF)
check_function_exists(atanh HAVE_ATANH)
check_function_exists(atoll HAVE_ATOLL)
check_function_exists(chroot HAVE_CHROOT)
check_function_exists(crypt_r HAVE_CRYPT_R)
check_function_exists(ctermid HAVE_CTERMID)
check_function_exists(ctime_r HAVE_CTIME_R)

check_function_exists(cuserid HAVE_CUSERID)

check_function_exists(acosh HAVE_ACOSH)
check_function_exists(alloca HAVE_ALLOCA)
check_function_exists(asinh HAVE_ASINH)
check_function_exists(atanh HAVE_ATANH)
check_function_exists(crypt_r HAVE_CRYPT_R)
check_function_exists(cuserid HAVE_CUSERID)
check_function_exists(flock HAVE_FLOCK)
check_function_exists(fnmatch HAVE_FNMATCH)
check_function_exists(fork HAVE_FORK)
check_function_exists(ftok HAVE_FTOK)
check_function_exists(gai_strerror HAVE_GAI_STRERROR)
check_function_exists(gcvt HAVE_GCVT)
check_function_exists(getaddrinfo HAVE_GETADDRINFO)
check_function_exists(getcwd HAVE_GETCWD)
check_function_exists(getgrgid_r HAVE_GETGRGID_R)
check_function_exists(getgrnam_r HAVE_GETGRNAM_R)
check_function_exists(getgroups HAVE_GETGROUPS)
check_function_exists(gethostname HAVE_GETHOSTNAME)
check_function_exists(getloadavg HAVE_GETLOADAVG)
check_function_exists(getlogin HAVE_GETLOGIN)
check_function_exists(getopt HAVE_GETOPT)
check_function_exists(getpgid HAVE_GETPGID)
check_function_exists(getprotobyname HAVE_GETPROTOBYNAME)
check_function_exists(getprotobynumber HAVE_GETPROTOBYNUMBER)
check_function_exists(getpwnam_r HAVE_GETPWNAM_R)
check_function_exists(getpwuid_r HAVE_GETPWUID_R)
check_function_exists(getrlimit HAVE_GETRLIMIT)
check_function_exists(getrusage HAVE_GETRUSAGE)
check_function_exists(getservbyname HAVE_GETSERVBYNAME)
check_function_exists(getservbyport HAVE_GETSERVBYPORT)
check_function_exists(getsid HAVE_GETSID)
check_function_exists(gettimeofday HAVE_GETTIMEOFDAY)
check_function_exists(getwd HAVE_GETWD)
check_function_exists(gmtime_r HAVE_GMTIME_R)
check_function_exists(grantpt HAVE_GRANTPT)
check_function_exists(hypot HAVE_HYPOT)
check_function_exists(inet_ntoa HAVE_INET_NTOA)
check_function_exists(inet_ntop HAVE_INET_NTOP)
check_function_exists(inet_pton HAVE_INET_PTON)
check_function_exists(initgroups HAVE_INITGROUPS)
check_function_exists(isascii HAVE_ISASCII)
check_function_exists(lchown HAVE_LCHOWN)
check_function_exists(log1p HAVE_LOG1P)
check_function_exists(mblen HAVE_MBLEN)
check_function_exists(mbrlen HAVE_MBRLEN)
check_function_exists(mbsinit HAVE_MBSINIT)
check_function_exists(memmove HAVE_MEMMOVE)
check_function_exists(mempcpy HAVE_MEMPCPY)
check_function_exists(mkfifo HAVE_MKFIFO)
check_function_exists(mknod HAVE_MKNOD)
check_function_exists(mkstemp HAVE_MKSTEMP)
check_function_exists(mmap HAVE_MMAP)
check_function_exists(mprotect HAVE_MPROTECT)
check_function_exists(mremap HAVE_MREMAP)
check_function_exists(nanosleep HAVE_NANOSLEEP)
check_function_exists(nice HAVE_NICE)
check_function_exists(nl_langinfo HAVE_NL_LANGINFO)
check_function_exists(perror HAVE_PERROR)
check_function_exists(poll HAVE_POLL)
check_function_exists(ptsname HAVE_PTSNAME)
check_function_exists(putenv HAVE_PUTENV)
check_function_exists(random HAVE_RANDOM)
check_function_exists(rand_r HAVE_RAND_R)
check_function_exists(realpath HAVE_REALPATH)
check_function_exists(scandir HAVE_SCANDIR)
check_function_exists(setegid HAVE_SETEGID)
check_function_exists(setenv HAVE_SETENV)
check_function_exists(seteuid HAVE_SETEUID)
check_function_exists(setitimer HAVE_SETITIMER)
check_function_exists(setlocale HAVE_SETLOCALE)
check_function_exists(setpgid HAVE_SETPGID)
check_function_exists(setrlimit HAVE_SETRLIMIT)
check_function_exists(setsid HAVE_SETSID)
check_function_exists(setsockopt HAVE_SETSOCKOPT)
check_function_exists(setvbuf HAVE_SETVBUF)
check_function_exists(shutdown HAVE_SHUTDOWN)
check_function_exists(sigprocmask HAVE_SIGPROCMASK)
check_function_exists(sin HAVE_SIN)
check_function_exists(snprintf HAVE_SNPRINTF)
check_function_exists(socketpair HAVE_SOCKETPAIR)
check_function_exists(socketpair HAVE_SOCKETPAIR)
check_function_exists(sqlite3_errstr HAVE_SQLITE3_ERRSTR)
check_function_exists(sqlite3_errstr HAVE_SQLITE3_ERRSTR)
check_function_exists(srand48 HAVE_SRAND48)
check_function_exists(srandom HAVE_SRANDOM)
check_function_exists(statfs HAVE_STATFS)
check_function_exists(statvfs HAVE_STATVFS)
check_function_exists(strcasecmp HAVE_STRCASECMP)
check_function_exists(__sync_fetch_and_add HAVE_SYNC_FETCH_AND_ADD)
check_function_exists(tempnam HAVE_TEMPNAM)
check_function_exists(tzset HAVE_TZSET)
check_function_exists(unlockpt HAVE_UNLOCKPT)
check_function_exists(unsetenv HAVE_UNSETENV)
check_function_exists(usleep HAVE_USLEEP)
check_function_exists(vasprintf HAVE_VASPRINTF)
check_function_exists(vsnprintf HAVE_VSNPRINTF)

